// <auto-generated />
using BookCatalog.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookCatalog.Migrations
{
    [DbContext(typeof(BookDbContext))]
    partial class BookDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookCatalog.Models.Author", b =>
                {
                    b.Property<int>("AuthorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuthorId"));

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AuthorId");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            AuthorId = 1,
                            Bio = "Джоан Роулинг е британска писателка, известна с поредицата за \"Хари Потър\". Тя създава магическия свят на Хогуортс, който завладява милиони читатели.",
                            ImagePath = "/images/rowling.jpg",
                            Name = "J.K. Rowling"
                        },
                        new
                        {
                            AuthorId = 2,
                            Bio = "Стивън Кинг е американски писател, наричан \"Кралят на ужаса\". Неговите романи са адаптирани в множество филми и сериали.",
                            ImagePath = "/images/king.jpg",
                            Name = "Stephen King"
                        },
                        new
                        {
                            AuthorId = 3,
                            Bio = "Агата Кристи е британска писателка, известна с криминалните си романи. Тя е автор на някои от най-продаваните книги в света.",
                            ImagePath = "/images/christie.jpg",
                            Name = "Agatha Christie"
                        },
                        new
                        {
                            AuthorId = 4,
                            Bio = "Джордж Р.Р. Мартин е американски писател, известен с фентъзи поредицата си \"Песен за огън и лед\", която вдъхновява сериала \"Игра на тронове\".",
                            ImagePath = "/images/martin.jpg",
                            Name = "G.R.R. Martin"
                        });
                });

            modelBuilder.Entity("BookCatalog.Models.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookId"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("BookInformation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BookId");

                    b.HasIndex("AuthorId");

                    b.HasIndex("GenreId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            AuthorId = 1,
                            BookInformation = "",
                            GenreId = 1,
                            ImagePath = "/images/gatsby.jpg",
                            Title = "The Great Gatsby"
                        },
                        new
                        {
                            BookId = 2,
                            AuthorId = 2,
                            BookInformation = "",
                            GenreId = 2,
                            ImagePath = "/images/mockingbird.jpg",
                            Title = "To Kill a Mockingbird"
                        },
                        new
                        {
                            BookId = 3,
                            AuthorId = 3,
                            BookInformation = "",
                            GenreId = 3,
                            ImagePath = "/images/1984.jpg",
                            Title = "1984"
                        },
                        new
                        {
                            BookId = 4,
                            AuthorId = 4,
                            BookInformation = "",
                            GenreId = 4,
                            ImagePath = "/images/pride.jpg",
                            Title = "Pride and Prejudice"
                        });
                });

            modelBuilder.Entity("BookCatalog.Models.BookTag", b =>
                {
                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("BookId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("BookTags");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            TagId = 1
                        },
                        new
                        {
                            BookId = 1,
                            TagId = 3
                        },
                        new
                        {
                            BookId = 2,
                            TagId = 1
                        },
                        new
                        {
                            BookId = 3,
                            TagId = 4
                        },
                        new
                        {
                            BookId = 4,
                            TagId = 3
                        });
                });

            modelBuilder.Entity("BookCatalog.Models.Genre", b =>
                {
                    b.Property<int>("GenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GenreId"));

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Info")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GenreId");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            GenreId = 1,
                            ImagePath = "/images/fantasy.jpg",
                            Info = "Потопете се в магически светове и епични приключения.",
                            Name = "Фентъзи"
                        },
                        new
                        {
                            GenreId = 2,
                            ImagePath = "/images/drama.jpg",
                            Info = "Изживейте интензивни разкази и силни емоции.",
                            Name = "Драма"
                        },
                        new
                        {
                            GenreId = 3,
                            ImagePath = "/images/sci-fi.jpg",
                            Info = "Започнете междузвездни пътешествия и космически приключения.",
                            Name = "Научна фантастика"
                        },
                        new
                        {
                            GenreId = 4,
                            ImagePath = "/images/romance.jpg",
                            Info = "Потопете се в сърдечни истории за любов и страст.",
                            Name = "Романтика"
                        });
                });

            modelBuilder.Entity("BookCatalog.Models.Tag", b =>
                {
                    b.Property<int>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TagId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TagId");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            TagId = 1,
                            Name = "Класика"
                        },
                        new
                        {
                            TagId = 2,
                            Name = "Трилър"
                        },
                        new
                        {
                            TagId = 3,
                            Name = "Любовна история"
                        },
                        new
                        {
                            TagId = 4,
                            Name = "Дистопия"
                        });
                });

            modelBuilder.Entity("BookCatalog.Models.Book", b =>
                {
                    b.HasOne("BookCatalog.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookCatalog.Models.Genre", "Genre")
                        .WithMany("Books")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("BookCatalog.Models.BookTag", b =>
                {
                    b.HasOne("BookCatalog.Models.Book", "Book")
                        .WithMany("BookTags")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookCatalog.Models.Tag", "Tag")
                        .WithMany("BookTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("BookCatalog.Models.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("BookCatalog.Models.Book", b =>
                {
                    b.Navigation("BookTags");
                });

            modelBuilder.Entity("BookCatalog.Models.Genre", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("BookCatalog.Models.Tag", b =>
                {
                    b.Navigation("BookTags");
                });
#pragma warning restore 612, 618
        }
    }
}
